FROM python:3.10.1-slim

#EXPOSE 8501

#WORKDIR /DS1016-Project

#RUN apt-get update && apt-get install -y \
#    build-essential \
#    software-properties-common \
#    git \
#    && rm -rf /var/lib/apt/lists/*
#RUN git clone https://github.com/Shaurynn/DS1016-Project.git .

COPY DS106-Project /DS1016-Project
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

#RUN apt-get install fsl

#ENV FSLDIR=/usr/share/fsl
#RUN . ${FSLDIR}/5.0/etc/fslconf/fsl.sh
#RUN PATH=${FSLDIR}/5.0/bin:${PATH}
#RUN export FSLDIR PATH

ENV INSTALL_FOLDER=/usr/local/
COPY fslinstaller.py ./
CMD python fslinstaller.py"]V FSLDIR=${INSTALL_FOLDER}/fsl/ \
    FSLOUTPUTTYPE=NIFTI_GZ
ENV FSL_PYTHON=${FSLDIR}/fslpython/envs/fslpython \
    PATH=${FSLDIR}/bin:$PATH \
    LD_LIBRARY_PATH=${FSLDIR}:${LD_LIBRARY_PATH}

ENTRYPOINT ["streamlit", "run", "server.py", "--server.port=8501", "--server.address=0.0.0.0"]
